name: Express CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Build and deploy
      run: |
        export APP_VERSION=v1.0.0
        echo "Setting APP_VERSION to $APP_VERSION"
        npm run build
        echo "Deploying version $APP_VERSION to production"
